logging:
  level:
    ROOT: INFO
    org.springframework.data: DEBUG

mongodb:
  uri:
    - "localhost:27017"
  database: "lotteryData"
  socketTimeout: 20_000
  connectTimeout: 20_000

lottery:
  latestDataURL: "https://bet.szerencsejatek.hu/cmsfiles/otos.csv"